apiVersion: v1
kind: pod
metadata:
  name: taint-pod
spec:
# list of conatiners
  containers:
  - name: taint-pod
    image: nginx
    #here with this line port will not be opned, just for information
    ports:
    - containerport: 80
  tolerations:
  - key: "project"
    operator: "Exists"
    effect: "NoSchedule"