apiVersion: v1
kind: pod
metadata:
  name: affinity-pod1
  namespace: roboshop
spec:
# list of conatiners
  containers:
  - name: affinity-pod1
    image: nginx
    #here with this line port will not be opned, just for information
    ports:
    - containerport: 80