apiVersion: v1
kind: pod
metadata:
  name: affinity-pod1
  labels:
   name: affinity-pod1
spec:
# list of conatiners
  containers:
  - name: affinity-pod1
    image: nginx
    #here with this line port will not be opned, just for information
    ports:
    - containerport: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: affinity-pod-2
spec:
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: name
            operator: In
            values:
            - affinity-pod-1
        topologyKey: topology.kubernetes.io/zone   
  containers:
  - name: with-pod-affinity
    image: nginx
