apiVersion: v1
kind: pod
metadata:
  name: label-demo
  labels:
   Course: DevOps
   Learner: "guru"
 spec:
# list of conatiners
  containers:
  - name: hello-pod
    image: nginx
    ports:
    - containerport: 80