apiVersion: v1
kind: pod
metadata:
  name: label-demo
  labels:
   Course: DevOps
   Learner: "guru"
  annotations:
   com.roboshop.learner.duration: "120hours"
   jenkins.url: "https://jenkins.com/roboshop/catalogue#45"
 spec:
# list of conatiners
  containers:
  - name: hello-pod
    image: nginx
    ports:
    - containerport: 80