apiVersion: v1
kind: pod
metadata:
  name: secret-pod
 spec:
# list of conatiners
  containers:
  - name: secret-pod
    image: nginx
    #here with this line port will not be opned, just for information
    ports:
    - containerport: 80
    envFrom:
    - configMapRef:
       name: devops-secret
   